version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: wp

  phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      ports:
        - 8080:80
      environment:
        MYSQL_ROOT_PASSOWRD: test

  wordpress:
    depends_on:
      - db
    image: wordpress:4.9.8
    links:
      - db:mysql
    ports:
      - 80:80
    restart: always
    volumes:
      - ./wp-content/themes/newTemplate:/var/www/html/wp-content/themes/newTemplate
    environment:
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: test