version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: wp

  phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      ports:
        - 8080:80
      environment:
        MYSQL_ROOT_PASSOWRD: test

  wordpress:
    depends_on:
      - db
    image: wordpress:5.1.1
    links:
      - db:mysql
    ports:
      - 80:80
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./wp-content/themes/newTemplate:/var/www/html/wp-content/themes/newTemplate
      # - ./wp-content/uploads:/var/www/html/wp-content/uploads # uploads folder
      # - ./wp-content/plugins:/var/www/html/wp-content/plugins # plugins folder
    environment:
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: test
      WORDPRESS_DEBUG: 1